DELETE http://localhost:3001/api/persons/64238297a2e9f2dc50a4a7c8

###

GET http://localhost:3001/api/persons/6421f4f41c43ae008906aaef

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "lailai",
  "number": "347-257-7792"
}

###

PUT http://localhost:3001/api/persons/6421f4f41c43ae008906aaf1
Content-Type: application/json

{
  "name": "bushilailai",
  "number": "SECRET TO YOU"
}