GET http://localhost:3001/api/notes/

### 

DELETE http://localhost:3001/api/notes/64222cf35e0e640baebe280d

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "HTMLS",
  "important": true
}